### ISSUE TITLE
tmap tm_polygons style error

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/CACommunityBurden#26]
If on the "Map (tmap)" tab the following are selected:
  geographic level: "Census Tract"
  Cut-point method: fisher
an error is generated because of missing values, noting that na.rm=TRUE is needed. 

Where/how can I set na.rm=TRUE or otherwise systematically address this error? (and not with an is.na(map.1$myMeasure) <- 0 type solution since this creates problems elsewhere). 

The key code is at lines 72-75 of the cbd-tmap.R file.

**Comment by zross** [comment]
There are two tabs that say "Map (TMAP)" I assume you mean the "MAP (TMAP LEAF)" version?

Is the error you're seeing preventing the map from being drawn (is the error on the UI? or in RStudio?). I'm not seeing this error.

Is this on the master branch? lines 72-75 are commented out.

![image](https://user-images.githubusercontent.com/1395177/44738433-dfce0b80-aac2-11e8-8f6a-da8b800f128e.png)

**Comment by mcSamuelDataSci** [comment]
The error is only when selecting the "quantile" cut-point method.

I have edited that file some--the note about this issue is now on lines 79-81.  On line 89 the "cut-point" method is selected based on the variable argument to the "style" parameter.

![capture](https://user-images.githubusercontent.com/19944056/44744411-9f878100-aaf4-11e8-9ea5-093ec88bd6da.PNG)

**Comment by zross** [comment]
It's not NA values causing issues it's infinite values. `tmap` doesn't like the infinite values. I'm not sure why you have Infinite but you can change with something like `data$plotter[is.infinite(data$plotter)] <- NA` and it should work.

The steps to solving this:

1. Break it down to simplest possible issue outside of Shiny if possible. I used a simple state shapefile, set a couple of values to NA and then used `tm_shape(state) + tm_polygons(col="CENSUSAREA",style="quantile",colorNA="white")` and it mapped fine. So it's not the NA values that are the problem.

2. Then I put `browser()` right before where the error was occurring. I counted how many `NA` values you have in the `plotter` field. Turned out to be none. So it's not NA.

3. I did a histogram of the `plotter` values and I'm seeing very high values.

4. I did a `tail(sort(data$plotter))` and I see you have `Inf` values. This is the issue.

**Comment by mcSamuelDataSci** [comment]
Perfect, thanks.
