### ISSUE TITLE
how to add stop() function to .ui or other proper location

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/CACommunityBurden#32]
Zev-

What is the proper way to add, and where should I put, something like this?:
if   (input$cZoom & input$myLHJ == "CALIFORNIA STATE" )   stop('Illogical Selection')

I have some similar statements (without the input$) WITHIN some functions, and that works fine, but there are some combinations of input values, like those above, that apply to several function/tabs, so would be more efficient to put in one place, rather than in each function.

Could alternatively be accomplished with next issue?

**Comment by zross** [comment]
With this and your other issue, it would be more helpful if you point be to specific lines of code for both issues I can't quite figure out what you're asking.

**Comment by mcSamuelDataSci** [comment]
This issue involves more than a few lines of code in one fine. I involves the relationships and interactivity of multiple things.  The error shown in the attached image is the result of their being no "CALIFORNIA STATE" data if "zoom to county" is selected. Zoom to county means, focus the map (or chart) on just one county, so if zooming, it does not make sense to then select "CALIFORNIA" as the jurisdiction being mapped.

So, two solutions that I could think of, are 1) to display a different drop-down list in the two situations, or 2) throw a meaningful error if that combination of inputs is selected. I can easily do 1) by using different inputID names, and 2) by adding the error message to each function that generates a map. BUT, there are other things coming along with this project, such that a "global" solution to this issue would be much better. 

I would be happy to do a webex soon to more clearly show you the issue, and I know that you would grasp it right away.

**Comment by mcSamuelDataSci** [comment]
![capture](https://user-images.githubusercontent.com/19944056/44924034-e943b780-acfe-11e8-8621-6f8e1644978a.JPG)

**Comment by zross** [comment]
I can look but won't be able to get to it until Monday or Tuesday.

**Comment by mcSamuelDataSci** [comment]
Monday or Tuesday would be great.  I will add two other issues before then, both small.  But one, it might be good to chat/webex if you would like?

**Comment by zross** [comment]
@nteetor he has three options and perhaps you can give this thought.

1) Easiest solution is what I added to a new branch (zr/git32_easy_option). Just use the full state if the user chooses California State. This seems like a good option here. See this commit: https://github.com/mcSamuelDataSci/CACommunityBurden/commit/8c00448efa36ec0bf35e23eb2769d86bb5c33d54

2) Return a message to the user if they choose California State. This is most complex but ultimately you'll likely want to be able to do this. The process here is that the `server.R` has a `cbdMapTL` output that uses `renderLeaflet()` that calls `cbdMapXLeaf()`. The `cbdMapXLeaf()` calls `cbdMapX()`.  If he wanted to return a message given some situation in the WHO app we used a `renderUI()` and then selectively returned a text message or a map. What do you think in this case? Might he do something like this? I did not include any sample code

3) Update the input so that "California State" does not occur in the list of choices. @mcSamuelDataSci I don't know where you're populating the county selection so I'm just giving you rough code options but if the user clicks on `input$cZoom` then you can update to drop that. I put commented out code in this commit https://github.com/mcSamuelDataSci/CACommunityBurden/commit/4212f91cc1e43d36639b66e15c1608832e81c2fd so you can see the general about how to do this.

**Comment by nteetor** [comment]
I would definitely encourage option 3. By removing the incorrect option the user avoids performing an unnecessary or useless action.

**Comment by mcSamuelDataSci** [comment]
All super helpful, thanks, and option 3 is certainly what I will use. 

IF something does arise, would it be reasonable to use something like the below in the server.R, or is my understand still way off:

observeEvent(input$cZoom,input$somethingElse {
  if(input$cZoom & !input$somethingElse) {stop('Michael you are a fool')
 }

**Comment by nteetor** [comment]
If you want to raise an error given a certain condition you can create a reactive to include in your render table or map functions, 

```R
checkZoom <- reactive({
  if (input$cZoom && !input$somethingElse) {
    stop("bad option selected")
  }
})

output$tableOfData <- renderTable({
  checkZoom()

  # ... other logic here
})
```
