### ISSUE TITLE
remove islands from maps

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/CACommunityBurden#36]
Zev-
I have tried a number of things to remove ALL the islands from the "shape files" I am working with, and nothing has worked, including the ms_filter_islands() function that I thought surely would. In [this demo file](https://github.com/mcSamuelDataSci/CACommunityBurden/blob/master/myUpstream/shapeWORK.R), I use ms_filter_islands--few changes to San Francisco, no changes to Los Angeles.  Please show me what I am doing wrong or provide another solution? Thanks.

**Comment by zross** [comment]
You should use a projected spatial file.  See my commit: https://github.com/mcSamuelDataSci/CACommunityBurden/commit/10863a29763ddb1b6696d63bf78294b73deff57f

![image](https://user-images.githubusercontent.com/1395177/45045388-c720a100-b040-11e8-83c2-bdec27934c8a.png)

**Comment by mcSamuelDataSci** [comment]
I intend to add projections for all maps, but was planning to wait until I have fully shifted to simple features and tmap, since other issues arise with some of the current maps if i shift now.

**Comment by zross** [comment]
You can project then unproject if you need to.

**Comment by mcSamuelDataSci** [comment]
I am missing something in your commit/answer/image above.  i am trying to get rid of all islands, since are are far off the coast and therefore make the map awkward at best.  The area approach you suggest seems it will not work since some census tracts are clearly smaller in area than some islands?

**Comment by zross** [comment]
Right. My comment says that approach "does not work here" but can be used with, say counties -- situations where the islands are distinctly smaller. But project and use `ms_filter_islands()` and this works.

**Comment by mcSamuelDataSci** [comment]
I thought there would be some "easy" way to remove any "shapes" that are outside the "main" shape object of the California "land" polygon. I saw some Stack-overflow comments to this end, but none that I could work out.

Regarding comment right above--okay, I will check this out...

**Comment by mcSamuelDataSci** [comment]
Sorry Zev, I am still not getting something through my thick skull. Doesn't the second line below project? 


la  <- filter(shape_Tract,COUNTYFP == "037")
la  <- st_transform(la, crs = proj1)
la  <- ms_filter_islands(la,min_area = 1000000)  
tm_shape(la) + tm_polygons(col="ALAND")

![rplot](https://user-images.githubusercontent.com/19944056/45048735-85d4c500-b031-11e8-96c5-2310a221574b.png)

**Comment by zross** [comment]
This issue took some digging. The long-story short version is that the polygons that look like islands are not technically islands. For LA, this is because there is a tiny notch of an additional tract and for SF it's because there is a tiny bit of of the "island" tract that is attached to the mainland.

I could probably write you a function to get you what you want exactly but it would take time to get right. Digging into this took time itself. So you might be better off identifying the tract codes for what you want to remove and doing it this way.

If you want me to spend more time explaining and commenting what I have below I can do it, but I assumed you didn't want me to spend more time. The code is in shapeWORK.R in the zr/git32_easy_option branch.

### Longer version of the story


Both SF and LA those are not really islands. For LA you can see there is a tiny additional notch in the middle island so you have two tracts there. And since the two big island pieces are a multipolygon neither will be treated as an island. With sf if you look at the "islands" carefully you can also see there is a tiny piece of that tract that is attached to the mainland.

![image](https://user-images.githubusercontent.com/1395177/45055514-ff82a800-b05d-11e8-8747-423bdbdbf891.png)

For sf you can "explode" the multipolygons into polygons and it will do mostly what you want then when you use `ms_filter_islands()`.

![image](https://user-images.githubusercontent.com/1395177/45055567-2d67ec80-b05e-11e8-86ed-a2bdbef097a5.png)

With LA, though you still have the "notch" to contend with as it's a different tract so you don't really have an island.

![image](https://user-images.githubusercontent.com/1395177/45055615-512b3280-b05e-11e8-99b7-20a31bd87a96.png)


If you use `st_relate()` to look at the relationships between the polygons you will find that there are four tract polygons (once exploded) that either have no spatial relationship with any other polygon or have just one relationship with another polygon. This includes the two islands, the notch and then one odd tiny sliver of land that you can't even see without zooming way in so you could potentially use this strategy.

![image](https://user-images.githubusercontent.com/1395177/45056083-dfec7f00-b05f-11e8-9418-ee12f2c453bd.png)

**Comment by mcSamuelDataSci** [comment]
This is incredibly helpful, and I will check a few things out, but it is likely that we would indeed like you to spend the time to get us exactly what we want.  We have some GIS folks that could probably do this "manually", but then there would be a hassle when it needs to be redone, AND, we are hoping this whole project can be used by other states at some point.  

I will let you know about spending more time on this by Friday.

**Comment by mcSamuelDataSci** [comment]
We would appreciate you writing a function to get exactly what we want if you can. If possible, great if it could be general beyond California, but California most important for us of course.

**Comment by mcSamuelDataSci** [comment]
Any rough timeline on when you might be able to get to this?

**Comment by zross** [comment]
OK the idea is to filter islands from counties and then use this filtered shapefile to mask tracts. I did the hard part -- the island filter from counties and if this is what you want then we can clip the tracts.

The script is [here](https://github.com/mcSamuelDataSci/CACommunityBurden/blob/master/myUpstream/islands_removal.R), see if it makes sense to you.

One of the things that made this a little more complex is that I think we don't want to lose islands that are, themselves, counties. So Nantucket, as an example, should not disappear. Here are the steps:

1. Explode the shapefile of counties so if a county is made up of multiple polygons then they each have their own records.

2. Filter out islands based on a minimum area

3. Identify if any counties disappeared entirely when filtering. 

4. If any counties disappeared (an island county), for each of these counties, identify the biggest piece and then filter out islands with areas that are smaller than the biggest piece.

5. Un-explode (dissolve) the filtered county dataset

6. Append back on the formerly missing counties.

**One of the nice aspects of this code is that you can use pretty much any minimum area, even very big ones, because it will find missing counties and put them back**



# For California

I used 1.01e+9 for minimum area

![image](https://user-images.githubusercontent.com/1395177/46038405-f9ba3880-c0d8-11e8-9c6c-c31ea4a060a6.png)

# For Massachusetts

I used 1.01e+9 for minimum area

![image](https://user-images.githubusercontent.com/1395177/46038501-3be37a00-c0d9-11e8-90de-ade9ced0f6bd.png)

**Comment by zross** [comment]
@nteetor is there a better way to do what I have as an if else in [this script](https://github.com/mcSamuelDataSci/CACommunityBurden/blob/master/myUpstream/islands_removal.R) related to nc/nr? Basically I'm saying if rowmap is TRUE then I want 1 column otherwise I want 1 row. Must be a simpler way to do this.

**Comment by nteetor** [comment]
Nothing wrong with the if/else's other than maybe swapping out the `=` for `<-`. 

The uses of `rbind()` can be replaced with dplyr's `bind_rows()`, unless this was already tried. If  using `bind_rows()` I don't think you will need the `do.call()`.

**Comment by mcSamuelDataSci** [comment]
The county_filter works great with the county file.  But with the more important tract file I get:

res <- county_filter(**tr_ca**, min_area = 1.01e+9, rowmap = FALSE)
Error in summarise_impl(.data, dots) : 
  Column `geometry` can't promote group 882 to list

I tried a couple different min_area and got the same error.

**Comment by mcSamuelDataSci** [comment]
I wanted to check that maybe my problem was some old packages. So I used it as an "opportunity" to really clean some things up.  I reinstalled R and all my packages. Dumb idea.  Any idea what this error below could be? I googled some, and did not find the answer. I will eventually, but just thought you might see some in this right away.

> library(tigris)
Error: package or namespace load failed for ‘tigris’ in library.dynam(lib, package, package.lib):
 DLL ‘stringi’ not found: maybe not installed for this architecture?

**Comment by mcSamuelDataSci** [comment]
Sorry for all the extra communication (and, happy to enter into additional contract?).  But I got tigris and everything else working. Needed to manually install stringi for some reason.  But, county_filter still not working fully, and actually seems like additional issues with all new packages, but likely something else on my side.  In any case, I get:

> res <- county_filter(cnty_ma, min_area = 2000000000)
Error in purrr::map(cnty_removed, ~island_county_processing(exploded_counties,  : 
  object 'cnty_removed' not found
Called from: purrr::map(cnty_removed, ~island_county_processing(exploded_counties, 
    .))
Browse[1]>

**Comment by zross** [comment]
The function is not supposed to work with tracts. Once county islands are removed we'll just essentially do an overlap and I haven't written that. Otherwise I'll take a look.

**Comment by mcSamuelDataSci** [comment]
Thanks. Our only need for this is with tract/community-level maps, like below
![capture](https://user-images.githubusercontent.com/19944056/46250283-3d1fea00-c3ec-11e8-9481-e477698b7574.JPG)

**Comment by zross** [comment]
Yes understood and that's what we're working towards.  You may remember from our discussion that using tracts **directly** could be problematic (perhaps even sort of impossible) because, as the example above shows, islands are not really islands because they have more than one tract. They are not a single geography surrounded by water. They are multiple geographies surrounded by water so it's not clear-cut how to define an island.

Counties don't have this issue. You won't have an island with multiple counties (I don't think).

So the process is:

1. Identify and eliminate islands using the county geography (using process above).
2. Once you have the perfect county geography, with islands dropped, you **overlay the county layer with the tract layer and only keep tract polygons that have a corresponding chunk in the counties**

The goal is tracts, but we start with counties.

So I just need to know if you're happy with how islands are defined and filtered in the county example, then I can write the last bit (which is easy) that overlays the tracts and counties.

Make sense?

**Comment by mcSamuelDataSci** [comment]
Sorry for the delayed reply.  Yes, makes sense.  I was not quite clear on how you determined the min_area for California and Massachusetts, but you did, and the values work, so that's the main thing. I look forward to the last bit.  Thanks.

**Comment by zross** [comment]
In the end minimum area won't really matter unless you have non-county islands that are really big, you might as well use a very big number since it will only remove islands that are not full counties.

I think all you need is `st_intersection()` once you have the county islands removed. Take a look at the code I added starting [here](https://github.com/mcSamuelDataSci/CACommunityBurden/blob/master/myUpstream/islands_removal.R#L92). Here are the tract maps limited to LA and then to Barnstable, Dukes and Nantucket counties for MA. These are before/after.

I fixed the issue you you raised about cnty_removed.

This should give you everything.

![image](https://user-images.githubusercontent.com/1395177/46424621-a616a300-c707-11e8-92de-8a5b6e57d005.png)

![image](https://user-images.githubusercontent.com/1395177/46424655-bc246380-c707-11e8-95f7-e66b2d42e2a4.png)

**Comment by mcSamuelDataSci** [comment]
The islands_removal is great and works perfectly for LA, Santa Barbara, and others and fine for SF. It does leave a couple pesky little islands for SF that would be good to get rid of if we can?  
![rplot](https://user-images.githubusercontent.com/19944056/46454193-e1da5880-c759-11e8-950f-91487fddd433.png)

**Comment by zross** [comment]
What does SF look like in the county layer? Those should definitely get removed!

**Comment by mcSamuelDataSci** [comment]
![rplot01](https://user-images.githubusercontent.com/19944056/46486420-97d19100-c7b2-11e8-9d52-749571547230.png)

**Comment by zross** [comment]
One of those is not an island as it's attached to Alameda County. The other is not an island in our definition because it's two counties on one chunk of land.

Can you, in words rather than code, specify how you'd like these handled? We could, initially, just dump all tiny sliver polygons -- below a certain area. I'm not sure if they are important in some places or not. So if we dumped any polygon below, perhaps 200,000 square meters first -- that would get rid of these two (they are 31589 and 145150), then run the islands filter and it would get rid of Angel Island State Park.

Let me know how you want to handle. 

![image](https://user-images.githubusercontent.com/1395177/46667924-0a6ab400-cb99-11e8-8488-c240b35eb49e.png)

**Comment by mcSamuelDataSci** [comment]
Zev-
Sorry for my delayed reply. After looking at all this, I think I need to not worry about Treasure Island and that weird bit of Alameda County that seems to be in San Francisco County. Treasure Island does have people living on it, so I guess it should be shown, and it does not "mess up" the view/zoom" of San Francisco. That other little thing is odd/annoying, but not worth removing via separate code I don't think. I will use your current island remove function, and check that everything looks just fine with that. Thanks.

**Comment by mcSamuelDataSci** [comment]
Zev-
Everything does look great for all counties except SF, with those two little chips in Alameda County and Angel Island (nothing to do with Treasure Island, as I miswrote above). Yes, if it is easy it would be good to remove those two chips based on their small area, UNLESS there is some chance we would remove "true" tracts or pieces thereof, or create other issues. 

Possibly related, I see that the new tract map object has 9014 "observations" rather than the original 8041, with 8031 unique GEOIDs. There are 5 tracts in CA that are 100% water, and some may be 100% Islands or something, so may well be that the 10 fewer GEOID is not an issue whatsoever.  And, the larger number of observations in the "new" tract object presumably has something to do with the "exploding", and is also not a problem as long as I left_join the map file with the data.
 
So, please do provide code to remove the chips if you think it is okay to do so.
