### ISSUE TITLE
map projection

### ISSUE THREAD

**Issue by mcSamuelDataSci** [mcSamuelDataSci/CACommunityBurden#39]
Somewhat related to #38: I still have not “projected” any of the shape files, and things are working fine. But, you have strongly encouraged projection of all shape files, so I intend to do so.  Is this better done when I generate the files [here](https://github.com/mcSamuelDataSci/CACommunityBurden/blob/master/myUpstream/shapeProcessor.R), or when I read them in [here](https://github.com/mcSamuelDataSci/CACommunityBurden/blob/master/myCBD/Global.R)?

**Comment by zross** [comment]
For any analysis, geoprocessing you should use projected versions. For static display projected versions are also preferable. For "slippy maps" like Google tiles etc you often can't change to projected.

To know when and when not to project in this particular app would take time because I'd have to figure out all the things that are happening and at what stages. If you are getting away with not projecting and functions are working it is up to you whether to proceed that way. None of your geoprocessing, I'm assuming needs to be super-accurate.

**Comment by mcSamuelDataSci** [comment]
thanks
